-- AlterTable
ALTER TABLE "users" ADD COLUMN     "balance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "expenses" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "income" DOUBLE PRECISION NOT NULL DEFAULT 0;
